# Generated by Django 3.0.5 on 2020-05-05 10:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_country', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2020, 5, 5, 10, 46, 49, 844031, tzinfo=utc), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=200)),
                ('style_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fichas.Client')),
            ],
        ),
    ]
