# Generated by Django 3.0.5 on 2020-05-05 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 10, 47, 3, 523187, tzinfo=utc), verbose_name='date published'),
        ),
    ]
