# Generated by Django 3.0.5 on 2020-05-04 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_client_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 4, 15, 32, 6, 479465, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='style_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
