# Generated by Django 3.0.5 on 2020-05-05 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0002_auto_20200505_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='style_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='style_price',
            new_name='price',
        ),
        migrations.AddField(
            model_name='ficha',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 10, 48, 44, 114156, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='edge_apint',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sku',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha',
            name='thread',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 10, 48, 44, 114156, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fichas.Client'),
        ),
        migrations.CreateModel(
            name='Lining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('roll_height', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moq', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fichas.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Leather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moq', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fichas.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('moq', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supplier', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fichas.Supplier')),
            ],
        ),
        migrations.AddField(
            model_name='ficha',
            name='lining',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fichas.Lining'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='upper',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fichas.Leather'),
        ),
    ]
