# Generated by Django 3.0.5 on 2020-05-05 14:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20200505_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='edge_apint',
            new_name='edge_paint',
        ),
        migrations.AlterField(
            model_name='client',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 14, 33, 49, 873328, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 14, 33, 49, 874326, tzinfo=utc), verbose_name='date published'),
        ),
    ]
